// exception handling 
let demo=()=>{
    try{
    let g=10;
    if(h==2)
    {
        console.log("condition true")
    }
    else{
        console.log("conditon false")
    }
    
}
catch(err){
    console.log(err.message)
}
}
demo()